<?php

namespace ContainerCPttknx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IBlHKjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iBlH_kj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iBlH_kj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientRegistry' => ['privates', '.errored.dpkpFT4', NULL, 'Cannot determine controller argument for "App\\Controller\\GoogleOAuthController::connectAction()": the $clientRegistry argument is type-hinted with the non-existent class or interface: "App\\Controller\\ClientRegistry". Did you forget to add a use statement?'],
        ], [
            'clientRegistry' => '?',
        ]);
    }
}
