<?php

namespace ContainerWvoezkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HokdgZZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hokdgZZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hokdgZZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientRegistry' => ['privates', '.errored..service_locator.hokdgZZ.KnpU\\OAuth2ClientBundle\\Client\\ClientRegistry', NULL, 'Cannot autowire service ".service_locator.hokdgZZ": it references class "KnpU\\OAuth2ClientBundle\\Client\\ClientRegistry" but no such service exists.'],
        ], [
            'clientRegistry' => 'KnpU\\OAuth2ClientBundle\\Client\\ClientRegistry',
        ]);
    }
}
