<?php

namespace ContainerWvoezkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hokdgZZ.KnpU\OAuth2ClientBundle\Client\ClientRegistry' shared service.
     *
     * @return \KnpU\OAuth2ClientBundle\Client\ClientRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hokdgZZ": it references class "KnpU\\OAuth2ClientBundle\\Client\\ClientRegistry" but no such service exists.');
    }
}
