<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWvoezkn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWvoezkn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWvoezkn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWvoezkn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWvoezkn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wvoezkn',
    'container.build_id' => '85b6b765',
    'container.build_time' => 1708934830,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWvoezkn');
