<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR2n6SF7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR2n6SF7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR2n6SF7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR2n6SF7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR2n6SF7\App_KernelDevDebugContainer([
    'container.build_hash' => 'R2n6SF7',
    'container.build_id' => 'eab09555',
    'container.build_time' => 1709039037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR2n6SF7');
